spring:
  application:
    name: tkp
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:4b
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      chroma:
        base-url: http://localhost:8000
        collection-name: documents