spring:
  application:
    name: tkp
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:4b
      embedding:
        options:
          model: nomic-embed-text
