spring:
  application:
    name: tkp
  ai:
    ollama:
      base-url: http://10.96.64.54:11434
      chat:
        options:
          model: qwen3:4b
      
app:
  chroma:
    enabled: false
    url: http://localhost:8000
    collection-name: documents
    embedding-dimension: 384

logging:
  level:
    org.springframework.ai.chroma: DEBUG
    org.springframework.web.client: DEBUG